### ISSUE TITLE
Issue with rust 1.47 while building the discovery handler docker file -  rust version 1.54 fixes this.

### ISSUE THREAD

**Issue by vinaypuranik** [deislabs/akri-discovery-handler-template#2]
Hi,

I tried to build the discovery handler docker and was facing the below error related to tower-http as shown in the screenshot. Later figured out that if we update the rust version to 1.54 it fixes the issue.  Perhaps somebody can update the dockerfile with the 1.54 rust version  ?!?

![image](https://user-images.githubusercontent.com/6823168/132879212-0e68712f-7a08-4f77-82a5-7a1919a7db2c.png)

```
FROM amd64/rust:1.54 as build
RUN rustup component add rustfmt --toolchain 1.54.0-x86_64-unknown-linux-gnu
RUN USER=root cargo new --bin dh
WORKDIR /dh
COPY ./Cargo.toml ./Cargo.toml
RUN cargo build --release && \
    rm ./src/*.rs && \
    DEP_PATH=`echo "./target/release/deps/{{project-name}}*" | tr - _` && \
    rm $DEP_PATH
COPY ./src ./src
RUN cargo build --release

FROM amd64/debian:buster-slim
RUN apt-get update && \
    apt-get install -y --no-install-recommends libssl-dev && \
    apt-get clean
COPY --from=build /dh/target/release/{{project-name}} /{{project-name}}
ENTRYPOINT ["/{{project-name}}"]
```

**Comment by kate-goldenring** [comment]
@vinaypuranik great find! Would you be interested in contributing the fix?

**Comment by vinaypuranik** [comment]
Yeah, sure. I would need repo access to create PR

**Comment by kate-goldenring** [comment]
> Yeah, sure. I would need repo access to create PR

@vinaypuranik you should be able to fork the repository and then create a PR with the changes from that fork. This [blog](https://jarv.is/notes/how-to-pull-request-fork-github/) is a good summary of the proper workflow.

**Comment by vinaypuranik** [comment]
@kate-goldenring Ah, okay :) Thanks Kate.  I have created the PR for the same here -> https://github.com/deislabs/akri-discovery-handler-template/pull/3
